import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#300038",
        "on-primary": "#f4f1ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#000f21",
        "tertiary-container": "#f487ff",
        "on-secondary": "#def7ff",
        "tertiary-dim": "#8a009e",
        "primary-fixed-dim": "#8387ff",
        "inverse-on-surface": "#8e9eb7",
        "on-secondary-fixed": "#003a45",
        "surface-container-low": "#eaf1ff",
        "secondary-dim": "#005867",
        "on-surface": "#203044",
        "on-primary-fixed": "#000000",
        tertiary: "#9e00b4",
        "secondary-fixed": "#65e1ff",
        "surface-container-high": "#d2e4ff",
        surface: "#f4f6ff",
        "on-secondary-container": "#004f5d",
        background: "#f4f6ff",
        "tertiary-fixed-dim": "#ef6eff",
        "surface-variant": "#c9deff",
        "on-tertiary-container": "#580065",
        "surface-container-highest": "#c9deff",
        "error-dim": "#a70138",
        error: "#b41340",
        "on-primary-fixed-variant": "#0e009d",
        "inverse-primary": "#8083ff",
        "on-tertiary": "#ffeefb",
        "surface-dim": "#bdd6fc",
        "on-surface-variant": "#4d5d73",
        "error-container": "#f74b6d",
        "surface-tint": "#4647d3",
        "on-secondary-fixed-variant": "#005969",
        outline: "#68788f",
        "surface-container": "#dce9ff",
        "primary-fixed": "#9396ff",
        "secondary-container": "#65e1ff",
        "secondary-fixed-dim": "#48d4f3",
        primary: "#4647d3",
        secondary: "#006576",
        "tertiary-fixed": "#f487ff",
        "on-error-container": "#510017",
        "on-background": "#203044",
        "surface-bright": "#f4f6ff",
        "outline-variant": "#9eaec7",
        "primary-container": "#9396ff",
        "primary-dim": "#3939c7",
        "on-tertiary-fixed-variant": "#660075",
        "on-primary-container": "#0a0081",
        "on-error": "#ffefef",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
